import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'RTR next app',
    description: 'Generated by RTR code',
  }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">RTR</Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
           

          </div>

        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  )
}
